version: '3.8'

services:
  elliot:
    build: .  # Build from the Dockerfile in the current directory
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./src:/app/src  # Mounting the src directory
    ports:
      - "3020:80"  # Mapping port 80 inside the container to port 3000 on the host
